

export const INIT_APPLICATION = 'INIT_APPLICATION';
export const LOAD_ALL_SURVEY_SUCCESS = 'LOAD_ALL_SURVEY_SUCCESS';
export const NEW_SURVEY_CREATED = 'NEW_SURVEY_CREATED';





export const LOADING_HOME_PAGE = 'LOADING_HOME_PAGE';